// SPDX-License-Identifier: MPL-2.0
//
// Part of Auguth Labs open-source softwares.
// Built for the Rust Programming Language Ecosystem.
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// Copyright (c) 2026 Auguth Labs (OPC) Pvt Ltd, India

// ===============================================================================
// `````````````````````````````````` TRAIT INST `````````````````````````````````
// ===============================================================================

//! Provides the transformation pipeline for instance trait definitions.
//!
//! The module transforms an `#[inst(...)]` trait into its internal expanded
//! representation, including generated instance-counter const generics,
//! instance-node associated types, and instance sum types.
//!
//! The transformation is performed in separate phases for the trait generic
//! header, instance-node and instance-tuple associated types, which are unified by
//! [`TraitInst`]. A documentation-only `cfg(not(feature = "inst"))` representation 
//! is also generated by [`TraitInstDoc`] so the public instance-trait interface can
//! be documented without exposing its internal generated generics.
//!
//! The module also provides the bound and generic-argument helpers used to
//! resolve instance-trait bounds and inject placeholder instance arguments
//! during node transformation.
//!
//! Support-crate delegation is used to invoke the explicit instance-trait and
//! instance-node macro phases after the initial transformations.

// ===============================================================================
// ``````````````````````````````````` IMPORTS ```````````````````````````````````
// ===============================================================================

// --- Proc Macro Crates ---
use proc_macro2::{Span, TokenStream};
use quote::{ToTokens, format_ident, quote};
use syn::{
    AngleBracketedGenericArguments, Attribute, ConstParam, File, GenericArgument, GenericParam, Ident, ImplItem, ImplItemType, Item, ItemImpl, ItemTrait, ItemType, LitInt, Meta, Path, PathArguments, PathSegment, TraitBound, TraitItem, Type, TypeParamBound, parse_quote, punctuated::Punctuated, token::{Comma, PathSep, Plus}, visit::Visit, visit_mut::{self, VisitMut},
};

// --- Local Crate ---
use crate::{
    Extraction, Inst, Transformation, args::{BoundInstance, InstModelLength, 
        InstTupleArgs, InstanceIdents, InstanceModel, NodeArgs}, 
        errors::{ParseBug, ProcParseErr, TraitBug, TraitError}, 
        node::AccessArgsRef, 
};

// --- Proc Suite ---
use proc_suite::{DocAttr, IdentList, InsertDocs, IntList, SupportCrate, misc::*};

// ===============================================================================
// ```````````````````````````` TRAIT INST ENTRY-POINT ```````````````````````````
// ===============================================================================

/// Transforms an instance trait through the [`crate::inst`] macro pipeline.
///
/// An instance trait declares named instance parameters, which are lowered
/// into const generic instance counters. Instance-node associated types,
/// instance sum types, instance tuple types are also transformed into their 
/// generated representations.
///
/// Before transformation:
///
/// ```ignore
/// #[inst(Module, Function)]
/// trait Hasher {
///     #[node(..)]
///     type Hash;
///
///     #[tuple(..)]
///     type Tuple;
/// 
///     #[sum]
///     type Output;
/// }
/// ```
///
/// The source trait is transformed into an internal `cfg(not(feature = "int"))` form.
/// The [`SupportCrate`] provides the public crate path, which re-exports the
/// explicit macro entry points from the `instances-macro` crate. Generated
/// attributes therefore reference those macros through the support crate:
///
/// ```ignore
/// #[cfg(not(feature = "inst"))]
/// #[support_crate::instance_trait_explicit_target(0, 1)]
/// #[support_crate::instance_node_explicit_target]
/// trait Hasher<const __INST_0: u8, const __INST_1: u8> {
///     #[instance_sub(...)]
///     type Hash;
/// 
///     #[instance_sub(...)]
///     type Tuple;
///
///     type Output;
/// }
/// ```
///
/// The transformation of the trait header generics and the transformation
/// of `#[node(...)]` and `#[tuple(..)]` associated types are separate 
/// transformation phases.
/// 
/// They are independently applied and validated, but are unified as part of
/// the same [`TraitInst`] macro pipeline.
///
/// A separate `cfg(not(feature = "inst"))` copy is retained for rustdoc 
/// and contains the generated documentation for the instance trait, 
/// its instance nodes, and its instance sum types:
///
/// ```ignore
/// #[cfg(not(feature = "inst"))]
/// /// Documentation Disclaimer for Instance Traits
/// trait Hasher {
///     /// Documentation Disclaimer for Instance Nodes
///     type Hash;
/// 
///     /// Documentation Disclaimer for Instance Tuples
///     type Tuple;
/// }
/// ```
///
/// The documentation representation intentionally hides the generated
/// instance-counter generics. The public trait interface is documented in
/// terms of the instance macros provided by this crate; the generated
/// implementation form is an internal expansion detail.
///
/// Thus, the expanded implementation is used when `inst` is enabled,
/// while the documentation-oriented copy is used when `inst` is not enabled.
/// The transformation also adds the metadata required for delegated macro
/// expansion.
#[derive(Debug, Clone)]
pub struct TraitInst;

impl Transformation<File, TokenStream> for TraitInst {
    fn raw_transform(
        &self,
        transform: &mut File,
        context: &TokenStream,
    ) -> Result<(), proc_macro2::TokenStream> {
        if transform.items.len() > 1 {
            return Err(ParseBug::TooManyItemsToTransform {}.into());
        }
        let Some(Item::Trait(trait_)) = transform
            .items
            .iter_mut()
            .find(|item| matches!(item, Item::Trait(_)))
        else {
            return Err(TraitBug::FileContainsNoTrait {}.into());
        };
        let idents = match context.is_empty() {
            true => None,
            false => {
                let idents = IdentList::checked_extract(context, &())?;
                Some(idents)
            }
        };

        let mut doc_trait = trait_.clone();
        let mut addon = File {shebang: None, attrs: Vec::new(), items: Vec::new()};

        ItemTypeInst::checked_transform(&ItemTypeInst, &mut (&mut addon, trait_), &idents)?;
        if let Some(idents) = &idents {
            TraitGenericsInst::checked_transform(&TraitGenericsInst, trait_, idents)?;
        }
        cfg_feature_disclaimer(&mut trait_.attrs);
        trait_.attrs.insert(0, Inst::feature());

        for item in addon.items {
            transform.items.push(item);
        }

        TraitInstDoc::checked_transform(&TraitInstDoc, &mut doc_trait, &idents)?;
        doc_trait.attrs.insert(0, Inst::not_feature());
        transform.items.push(Item::Trait(doc_trait));

        Ok(())
    }

    fn validate_transform(
        &self,
        transform: &File,
        context: Option<&TokenStream>,
    ) -> Result<(), proc_macro2::TokenStream> {
        let find = |doc: bool, item: &Item| -> bool {
            let Item::Trait(trait_) = item else {
                return false;
            };
            trait_.attrs.iter().any(|attr| {
                if *attr == Inst::feature() {
                    if doc {false} else {true}
                } else if *attr == Inst::not_feature() {
                    if doc {true} else {false}

                } else {
                    false
                }
            }) 
        };
        let Some(doc_trait) = transform.items.iter().find(|item| find(true, item)) else {
            return Err(TraitBug::TransformedFileDoesNotHaveDocTarget {}.into());
        };
        let Some(not_doc_trait) = transform.items.iter().find(|item| find(false, item)) else {
            return Err(TraitBug::TransformedFileDoesNotHaveNotDocTarget {}.into());
        };

        let Item::Trait(trait_) = not_doc_trait else {
            unreachable!()
        };
        if !trait_.clone().has_docs() {
            return Err(TraitBug::NotDocTargetDoesNotHaveDocs {}.into());
        }

        if let Some(context) = context {
            if !context.is_empty() {
                let Item::Trait(trait_) = doc_trait else {
                    unreachable!()
                };
                if !trait_.clone().has_docs() {
                    return Err(TraitBug::DocTargetDoesNotHaveDocs {}.into());
                }
            }
        }

        Ok(())
    }
}

// ===============================================================================
// ```````````````````````````` TRAIT INST DOC-TARGET ````````````````````````````
// ===============================================================================

/// Transforms an instance trait into its documentation representation.
///
/// This transformation is applied to the `cfg(not(feature = "inst"))` copy produced by
/// [`TraitInst`]. It removes the internal `#[node(...)]`, `#[sum]` and #[tuple]
/// attributes and replaces them with generated rustdoc describing the
/// instance nodes and instance sum types.
///
/// For an instance trait, it also adds a trait-level description containing
/// its declared instance parameters and points users to the [`crate::inst`]
/// macros used to define and access instance traits.
///
/// Before transformation:
///
/// ```ignore
/// #[inst(Module, Function)]
/// trait Hasher {
///     #[node(Node(..))]
///     type Hash: Node;
///
///     #[tuple(..)]
///     type Tuple: Bound;
/// 
///     #[sum]
///     type Output;
/// }
/// ```
///
/// The documentation representation retains the user-facing trait while
/// replacing the instance-specific attributes with documentation:
///
/// ```ignore
/// /// # Instance Trait `(Module, Function)`
/// ///
/// /// An instance trait such as `Hasher` is implemented using
/// /// `#[inst(..)]` and its trait items are accessed through
/// /// `inst_get!()` or `inst_direct!()`.
/// trait Hasher {
///     /// # Instance Node [`Node`]
///     ///
///     /// An instance node associated accessed through `inst_get!()`.
///     type Hash;
///     
///     /// # Instance Tuple (`..`)
///     ///
///     /// An instance tuple ...
///     type Tuple;
///
///     /// # Instance Sum Type [`Hasher`]
///     ///
///     /// An instance sum type is interoperable across dynamic instances.
///     type Output;
/// }
/// ```
///
/// When no instance parameters are supplied, the transformation does not
/// permit `#[sum]` associated types, since instance sum types are only valid
/// for instance traits.
#[derive(Debug, Clone)]
pub struct TraitInstDoc;

impl Transformation<ItemTrait, Option<IdentList>> for TraitInstDoc {
    fn raw_transform(
        &self,
        transform: &mut ItemTrait,
        context: &Option<IdentList>,
    ) -> Result<(), proc_macro2::TokenStream> {
        let ident = transform.ident.clone();

        if let Some(idents) = context {
            transform.attrs.prepend_docs(vec![
                DocAttr::Heading {
                    level: 0,
                    content: vec![DocAttr::Raw(format!(
                        "Instance Trait `({})`",
                        idents.to_token_stream()
                    ))],
                },
                DocAttr::Raw(format!(
                    "An instance trait such as `{}` is implemented using ",
                    ident,
                )),
                DocAttr::Link {
                    title: "#[inst(..)]".to_string(),
                    url: "inst::inst".to_string(),
                },
                DocAttr::Raw(" and its trait items are accessed through ".to_string()),
                DocAttr::Link {
                    title: "inst_get!()".to_string(),
                    url: "inst::inst_get".to_string(),
                },
                DocAttr::Raw(" *or* ".to_string()),
                DocAttr::Link {
                    title: "inst_direct!()".to_string(),
                    url: "inst::inst_direct".to_string(),
                },
                DocAttr::Raw(".".to_string()),
                DocAttr::LineBreak,
                DocAttr::Raw("*See* ".to_string()),
                DocAttr::Link {
                    title: "`inst::trait`".to_string(),
                    url: "inst::trait".to_string(),
                },
                DocAttr::Raw(" *for instance trait definitions,* ".to_string()),
                DocAttr::Link {
                    title: "`inst::impl`".to_string(),
                    url: "inst::impl".to_string(),
                },
                DocAttr::Raw(" *for instance implementations.*".to_string()),
                DocAttr::LineBreak,
            ]);
        }

        for item in &mut transform.items {
            let TraitItem::Type(ty) = item else {
                continue;
            };

            let mut docs = Vec::new();
            let mut node = None;
            let mut tuple = None;
            let mut is_sum = false;

            let attrs = std::mem::take(&mut ty.attrs);
            let mut retained_attrs = Vec::with_capacity(attrs.len());

            let node_ident = Inst::node();
            let tuple_ident = Inst::tuple();
            let sum_ident = Inst::sum();

            for attr in attrs {
                let path_ident = attr.path().get_ident();

                if path_ident.is_some_and(|ident| *ident == node_ident) && path_ident.is_some_and(|ident| *ident == tuple_ident) {
                    return Err(TraitBug::EitherTupleOrNode {}.into())
                }

                match path_ident {
                    Some(ident) if *ident == node_ident => {
                        let tokens = match &attr.meta {
                            syn::Meta::List(meta_list) => &meta_list.tokens,
                            syn::Meta::Path(_) => {
                                return Err(TraitBug::NodeRequiresArgs {}.into());
                            }
                            syn::Meta::NameValue(_) => {
                                return Err(TraitBug::NodeRequiresArgsNotValue {}.into());
                            }
                        };

                        if tokens.is_empty() {
                            return Err(TraitBug::NodeRequiresArgs {}.into());
                        }

                        node = Some(BoundInstance::checked_extract(tokens, &())?);
                    }

                    Some(ident) if *ident == tuple_ident => {
                        let tokens = match &attr.meta {
                            syn::Meta::List(meta_list) => &meta_list.tokens,
                            syn::Meta::Path(_) => {
                                return Err(TraitBug::TupleRequiresArgs {}.into());
                            }
                            syn::Meta::NameValue(_) => {
                                return Err(TraitBug::TupleRequiresArgsNotValue {}.into());
                            }
                        };

                        if tokens.is_empty() {
                            return Err(TraitBug::TupleRequiresArgs {}.into());
                        }

                        tuple = Some(InstTupleArgs::checked_extract(tokens, &())?);
                    }

                    Some(ident) if *ident == sum_ident => {
                        if context.is_none() {
                            return Err(TraitError::SumNotAllowed { attr }.into());
                        }

                        if !matches!(&attr.meta, syn::Meta::Path(_)) {
                            return Err(TraitError::SumNoArgs { attr }.into());
                        }

                        is_sum = true;
                    }

                    _ => retained_attrs.push(attr),
                } 
            }

            ty.attrs = retained_attrs;

            if let Some(bound) = node {
                let path = bound.path.to_token_stream().to_string();

                docs.extend([
                    DocAttr::Heading {
                        level: 1,
                        content: vec![
                            DocAttr::Raw("Instance Node ".to_string()),
                            DocAttr::Ref(path),
                            DocAttr::Raw(format!("`{}`", bound.bound.to_token_stream())),
                        ],
                    },
                    DocAttr::Raw("An instance node associated accessed through ".to_string()),
                    DocAttr::Link {
                        title: "inst_get!()".to_string(),
                        url: "inst::inst_get".to_string(),
                    },
                    DocAttr::Raw(".".to_string()),
                    DocAttr::LineBreak,
                    DocAttr::Raw("*See* ".to_string()),
                    DocAttr::Link {
                        title: "`inst::node`".to_string(),
                        url: "inst::node".to_string(),
                    },
                    DocAttr::Raw(" *for instance node definitions and syntax.*".to_string()),
                    DocAttr::LineBreak,
                ]);
            }

            if let Some(tuples) = tuple {

                docs.extend([
                    DocAttr::Heading {
                        level: 1,
                        content: vec![
                            DocAttr::Raw("Instance Tuple".to_string()),
                        ],
                    },
                    DocAttr::Raw("This associated type has been tuple-destructured into the following individual types, each implementing ".to_string()),
                    DocAttr::Ref(format!("Self::{}", ty.ident.to_string())),
                    DocAttr::Raw("'s exact bounds".to_string()),
                    DocAttr::LineBreak,
                ]);

                for name in tuples.list() {
                    docs.push(
                        DocAttr::Bullet { level: 0, content: vec![DocAttr::Ref(name.to_string())] }
                    );
                }

                docs.extend([
                    DocAttr::LineBreak,
                    DocAttr::Raw(
                        "⚠️ **Warning:** Without `--features inst`, these individual types collapse \
                        to the default type supplied by the implementation; multiple types may \
                        therefore resolve to the same type."
                            .to_string(),
                    ),
                    DocAttr::LineBreak,
                    DocAttr::Raw("*See* ".to_string()),
                    DocAttr::Link {
                        title: "`inst::tuple`".to_string(),
                        url: "inst::tuple".to_string(),
                    },
                    DocAttr::Raw(" *for instance tuple definitions*".to_string()),
                    DocAttr::LineBreak,
                ]);
            }

            if is_sum {
                docs.extend([
                    DocAttr::Heading {
                        level: 1,
                        content: vec![
                            DocAttr::Raw("Instance Sum Type ".to_string()),
                            DocAttr::Ref(ident.to_string()),
                        ],
                    },
                    DocAttr::Raw(
                        "An instance sum type is interoperable across \
                         dynamic instances."
                            .to_string(),
                    ),
                    DocAttr::LineBreak,
                    DocAttr::Raw("*See* ".to_string()),
                    DocAttr::Link {
                        title: "`inst::sum`".to_string(),
                        url: "inst::sum".to_string(),
                    },
                    DocAttr::Raw(" *for instance sum type definitions.*".to_string()),
                    DocAttr::LineBreak,
                ]);
            }

            ty.attrs.prepend_docs(docs);
        }

        Ok(())
    }

    fn validate_transform(
        &self,
        transform: &ItemTrait,
        context: Option<&Option<IdentList>>,
    ) -> Result<(), proc_macro2::TokenStream> {
        if let Some(Some(_)) = context {
            if !&transform.attrs.clone().has_docs() {
                return Err(TraitBug::TraitDocsNotFound {}.into());
            }
        }

        for item in &transform.items {
            let TraitItem::Type(ty) = item else {
                continue;
            };
            if ty.attrs.iter().any(|attr| attr.path().is_ident(&Inst::sum())) {
                return Err(TraitBug::DocTargetInstTraitSumAttrExists {}.into());
            }
            if ty.attrs.iter().any(|attr| attr.path().is_ident(&Inst::node())) {
                return Err(TraitBug::DocTargetInstTraitNodeAttrExists {}.into());
            }
            if ty.attrs.iter().any(|attr| attr.path().is_ident(&Inst::tuple())) {
                return Err(TraitBug::DocTargetInstTraitTupleAttrExists {}.into());
            }
        }
        Ok(())
    }
}

// ===============================================================================
// `````````````````````````` INST TRAIT GENERICS HEADER `````````````````````````
// ===============================================================================

/// Transforms the generic header of an instance trait.
///
/// For every declared instance parameter, this phase inserts a generated
/// `u8` const generic used as the instance counter. The generated counters
/// are inserted after all lifetime parameters and their generic position indexes are
/// recorded in `instance_trait_explicit_target` delegated attribute arguments.
///
/// This phase is independent of the transformation of instance-node
/// associated types. Both transformations are executed as part of the same
/// [`TraitInst`] pipeline.
///
/// Before transformation:
///
/// ```ignore
/// #[inst(Module, Function)]
/// trait Hasher<'a, T> {
///     // ...
/// }
/// ```
///
/// After transformation:
///
/// ```ignore
/// #[instance_trait_explicit_target(2, 3)]
/// trait Hasher<'a, T, const __INST_0: u8, const __INST_1: u8> {
///     // ...
/// }
/// ```
///
/// The indexes `2` and `3` identify the positions of the generated instance
/// counters in the trait's generic parameter list. Existing lifetime
/// parameters remain at the front, while the generated instance counters are
/// inserted before other non-lifetime parameters when applicable.
///
/// The `instance_trait_explicit_target` attribute records the generic indexes,
/// while [`SupportCrate::delegate_attribute`] appends the delegate macro for
/// the final transformation by [`crate::delegate_support_crate_internal_only`].
#[derive(Debug, Clone)]
struct TraitGenericsInst;

impl Transformation<ItemTrait, IdentList> for TraitGenericsInst {
    fn raw_transform(
        &self,
        transform: &mut ItemTrait,
        context: &IdentList,
    ) -> Result<(), proc_macro2::TokenStream> {
        if context.idents.len() > 4 {
            return Err(TraitError::Max4Params {
                idents: context.clone(),
            }
            .into());
        }
        // generic params (for each instance counter)
        let mut collect = Vec::new();
        for (i, _) in context.idents.iter().enumerate() {
            let id_str = i.to_string();
            let id = id_str.as_bytes();
            let ident = gen_const_ident_with_suffix::<TraitInst>(Some(id));
            collect.push(GenericParam::Const(ConstParam {
                attrs: Default::default(),
                const_token: Default::default(),
                ident,
                colon_token: Default::default(),
                ty: parse_quote!(u8),
                eq_token: Default::default(),
                default: Default::default(),
            }));
        }

        let params = &mut transform.generics.params;

        // only append params after lifetimes
        let mut seen_non_lifetime = false;
        for param in params.iter() {
            if let GenericParam::Lifetime(lt) = param {
                if seen_non_lifetime {
                    return Err(ProcParseErr::LifetimeShouldBeDeclaredFront {
                        lt: lt.lifetime.clone(),
                    }
                    .into());
                }
            } else {
                seen_non_lifetime = true;
            }
        }

        let index = params
            .iter()
            .position(|param| !matches!(param, GenericParam::Lifetime(_)))
            .unwrap_or(params.len());

        let mut indexes = Vec::new();
        for (offset, param) in collect.into_iter().enumerate() {
            let offsetted = index + offset;
            params.insert(offsetted, param);
            indexes.push(LitInt::new(&offsetted.to_string(), Span::call_site()));
        }

        let attrs = &mut transform.attrs;

        let support_crate = Inst::support_crate();
        let trait_target = Inst::trait_target();
        attrs.insert(
            0,
            parse_quote!(#[#support_crate::#trait_target(#(#indexes),*)]),
        );
        Inst::delegate_attribute(attrs);

        for item in &mut transform.items {
            let TraitItem::Type(ty) = item else {
                continue;
            };
            if ty.attrs.iter().any(|attr| attr.path().is_ident(&Inst::sum())) {
                cfg_feature_disclaimer(ty);
            }
        }

        Ok(())
    }

    fn validate_transform(
        &self,
        transform: &ItemTrait,
        context: Option<&IdentList>,
    ) -> Result<(), proc_macro2::TokenStream> {
        let support_crate = Inst::support_crate();
        let Some(delegate_macro) = Inst::delegate_macro() else {
            return Err(TraitBug::DelegateMacroNotInitialized {}.into());
        };

        let Some((idx, inst_attr)) = transform.attrs.iter().enumerate().find_map(|(i, attr)| {
            let trait_target = Inst::trait_target();
            if *attr.path() == parse_quote!(#support_crate::#trait_target) {
                return Some((i, attr));
            }
            return None;
        }) else {
            return Err(TraitBug::InstanceTraitMacroNotFound {}.into());
        };

        if !transform.attrs.iter().enumerate().any(|(i, attr)| {
            if i <= idx {
                return false;
            }
            *attr.path() == parse_quote!(#support_crate::#delegate_macro)
        }) {
            return Err(TraitBug::DelegateMacroNotFound {}.into());
        }

        let tokens = match &inst_attr.meta {
            syn::Meta::List(meta_list) => &meta_list.tokens,
            _ => return Err(TraitBug::InstanceTraitMacroArgsNotFound {}.into()),
        };

        let Ok(indexes) = IntList::checked_extract(tokens, &()) else {
            return Err(TraitBug::InstanceTraitMacroIndexesParseFailed {}.into());
        };

        let Some(context) = context else {
            return Ok(());
        };

        let params = &transform.generics.params;
        let mut seen_non_lifetime = false;
        for param in params.iter() {
            if matches!(param, GenericParam::Lifetime(_)) {
                if seen_non_lifetime {
                    return Err(ParseBug::LifetimeShouldBeDeclaredFront {}.into());
                }
            } else {
                seen_non_lifetime = true;
            }
        }
        let mut index = params
            .iter()
            .position(|param| !matches!(param, GenericParam::Lifetime(_)))
            .unwrap_or(params.len());

        let mut collect = Vec::new();
        for (i, _) in context.idents.iter().enumerate() {
            let id_str = i.to_string();
            let id = id_str.as_bytes();
            let ident = gen_const_ident_with_suffix::<TraitInst>(Some(id));
            collect.push((index.clone(), ident));
            index = index + 1;
        }

        if collect.len() != indexes.ints.len() {
            return Err(TraitBug::InstanceTraitMacroIndexesInconsistent {}.into());
        }

        for ((index, ident), int) in collect.into_iter().zip(indexes.ints) {
            if index != parse_pos_usize(&int)? {
                return Err(TraitBug::InstanceCounterIndexInvalid {}.into());
            }

            let Some(param) = params.get(index) else {
                return Err(TraitBug::InstanceCounterConstNotFound {}.into());
            };

            let GenericParam::Const(c) = param else {
                return Err(TraitBug::InstanceCounterGenericNotConst {}.into());
            };

            if c.ident != ident {
                return Err(TraitBug::InstanceCounterGenericInvalidIdent {}.into());
            }

            if c.ty != parse_quote!(u8) {
                return Err(TraitBug::InstanceCounterGenericInvalidType {}.into());
            }
        }

        Ok(())
    }
}

// ===============================================================================
// `````````````````````````` INST TRAIT ASSOCIATE TYPES `````````````````````````
// ===============================================================================

/// Transforms instance type associated items declared on an instance trait.
///
/// The transformation validates the instance-specific associated types
/// declared on the trait and dispatches their transformation to the
/// corresponding instance type transformation.
///
/// An associated type may contain either `#[node(...)]` or `#[tuple(...)]`,
/// but not both. Instance node and tuple attributes are only valid on
/// associated type items; using either attribute on an associated constant or
/// function produces an error.
///
/// The transformation also validates references to the containing trait from
/// instance type declarations when invoked in the nested transformation
/// context. Such references are rejected to prevent an instance trait from
/// recursively referring to itself through its generated instance types.
///
/// At least one instance type declaration is required when transforming an
/// instance trait directly. When invoked from a nested transformation, the
/// absence of an instance type declaration is allowed.
///
/// After validation, the transformation delegates the actual generation to:
///
/// - [`ItemTypeNodeInst`] for `#[node(...)]` associated types, including their
///   generated instance node representations and access implementations, and
/// - [`ItemTypeTupleInst`] for `#[tuple(...)]` associated types, including their
///   generated instance tuple representations and access implementations.
///
/// This transformation therefore acts as the entry point for instance
/// associated type processing, while the node and tuple transformations own
/// the generation of their respective representations and access machinery.
#[derive(Debug, Clone)]
struct ItemTypeInst;

type AddonSpace<'a> = (&'a mut File, &'a mut ItemTrait);

impl<'a> Transformation<AddonSpace<'a>, Option<IdentList>> for ItemTypeInst {
    fn raw_transform(&self, transform: &mut AddonSpace<'a>, context: &Option<IdentList>) -> Result<(), proc_macro2::TokenStream> {
        let trait_ = &mut transform.1;

        let node = Inst::node();
        let tuple = Inst::tuple();

        struct VisitIdent {
            exp: Ident,
            found: Option<Ident>
        }

        impl<'ast> Visit<'ast> for VisitIdent {
            fn visit_ident(&mut self, i: &'ast proc_macro2::Ident) {
                if *i == self.exp {
                    self.found = Some(i.clone());
                }
                return 
            }
        }

        let trait_ident = &trait_.ident;
        let mut found = false;

        for item in &trait_.items {
            match item {
                TraitItem::Const(c) => {
                    if let Some(attr) = c.attrs.iter().find(|attr| attr.path().is_ident(&node))
                    {
                        return Err(
                            TraitError::NodeOnlyInTypeAssoc { attr: attr.clone() }.into()
                        );
                    }

                    if let Some(attr) = c.attrs.iter().find(|attr| attr.path().is_ident(&tuple))
                    {
                        return Err(
                            TraitError::TupleOnlyInTypeAssoc { attr: attr.clone() }.into()
                        );
                    }
                }
                TraitItem::Fn(f) => {
                    if let Some(attr) = f.attrs.iter().find(|attr| attr.path().is_ident(&node))
                    {
                        return Err(
                            TraitError::NodeOnlyInTypeAssoc { attr: attr.clone() }.into()
                        );
                    }
                    if let Some(attr) = f.attrs.iter().find(|attr| attr.path().is_ident(&tuple))
                    {
                        return Err(
                            TraitError::TupleOnlyInTypeAssoc { attr: attr.clone() }.into()
                        );
                    }
                }
                TraitItem::Type(t) => {
                    let node = t.attrs.iter().find(|attr| attr.path().is_ident(&Inst::node()));
                    let tuple = t.attrs.iter().find(|attr| attr.path().is_ident(&Inst::tuple()));

                    if node.is_some() && tuple.is_some() {
                        return Err(TraitError::EitherTupleOrNode { attr: tuple.unwrap().clone() } .into())
                    }

                    if node.is_some() || tuple.is_some() {
                        if context.is_some() {
                            let mut visitor = VisitIdent {exp: trait_ident.clone(), found: None};
                            visitor.visit_trait_item_type(&t);
                            if let Some(ident) = visitor.found {
                                return Err(TraitError::InstTraitOverflowReference {ident}.into());
                            }
                        }
                        found = true;
                    }
                }
                _ => {}
            }
        }
        if !found && context.is_none() {
            return Err(TraitError::InstEitherTraitOrNodeOrTuple {}.into());
        }

        ItemTypeNodeInst::checked_transform(&ItemTypeNodeInst, &mut transform.1, &())?;
        ItemTypeTupleInst::checked_transform(&ItemTypeTupleInst, transform, &())?;
        Ok(())
    }

    fn validate_transform(&self, transform: &AddonSpace<'a>, _: Option<&Option<IdentList>>) -> Result<(), proc_macro2::TokenStream> {
        ItemTypeNodeInst::validate_transform(&ItemTypeNodeInst, &transform.1, None)?;
        ItemTypeTupleInst::validate_transform(&ItemTypeTupleInst, transform, None)?;
        Ok(())
    }
}

// ===============================================================================
// ````````````````````````````` INST ASSOC TYPE NODE ````````````````````````````
// ===============================================================================

/// Transforms instance-node associated types declared on an instance trait.
///
/// Each `#[node(...)]` attribute is parsed as a [`BoundInstance`], its
/// instance-trait bound is resolved, and the instance model is lowered into
/// [`NodeArgs`]. The resulting node arguments are attached as an internal
/// `#[instance_sub(...)]` attribute annotation consumed by delegated attribute macro
/// `instance_node_explicit_target`.
///
/// `#[node(...)]` is only valid on associated types; constants and functions
/// cannot declare instance nodes.
///
/// The `instance_node_explicit_target` attribute is then added to the trait,
/// and [`SupportCrate::delegate_attribute`] appends the delegate macro for
/// the final transformation by [`crate::delegate_support_crate_internal_only`].
///
/// Before transformation:
///
/// ```ignore
/// #[node(Crypto::Hasher(Module, Function))]
/// type Hash;
/// ```
///
/// After this phase:
///
/// ```ignore
/// #[instance_sub(...)]
/// type Hash;
///
/// // and on the trait
///
/// #[support_crate::instance_node_explicit_target]
/// #[support_crate::delegate_support_crate_internal_only]
/// trait Hasher { ... }
/// ```
///
/// The transformation of the node arguments is performed separately from the
/// trait generic-header transformation, but both phases are unified by the
/// [`TraitInst`] pipeline.
#[derive(Debug, Clone)]
struct ItemTypeNodeInst;

impl Transformation<ItemTrait> for ItemTypeNodeInst {
    fn raw_transform(
        &self,
        transform: &mut ItemTrait,
        _: &(),
    ) -> Result<(), proc_macro2::TokenStream> {
        let node = Inst::node();

        let mut ty_items = Vec::new();
        for item in &mut transform.items {
            if let TraitItem::Type(t) = item {
                if t.attrs.iter().any(|attr| attr.path().is_ident(&node)) {
                    ty_items.push(t);
                }
            }
        }

        for ty in ty_items {
            let mut node_attr = None;
            let mut build = Vec::new();
            for attr in &ty.attrs {
                if !attr.path().is_ident(&node) {
                    build.push(attr.clone());
                    continue;
                }
                if node_attr.is_some() {
                    return Err(TraitError::DoubleNode { attr: attr.clone() }.into());
                };
                node_attr = Some(attr.clone());
            }
            ty.attrs = build;
            let Some(node_attr) = node_attr else {
                return Err(TraitBug::InconsistencyFindingNodeAttribute {}.into());
            };

            let tokens = match &node_attr.meta {
                syn::Meta::List(meta_list) => &meta_list.tokens,
                syn::Meta::Path(_) => {
                    return Err(TraitError::NodeRequiresArgs {
                        attr: node_attr.clone(),
                    }
                    .into());
                }
                syn::Meta::NameValue(meta) => {
                    return Err(TraitError::NodeRequiresArgsNotValue { meta: meta.clone() }.into());
                }
            };
            if tokens.is_empty() {
                return Err(TraitError::NodeRequiresArgs {
                    attr: node_attr.clone(),
                }
                .into());
            }

            let inst = BoundInstance::checked_extract(tokens, &())?;

            let indexes = append_placeholder_args(&mut ty.bounds, &inst.path, &inst.bound, true)?;

            let node_args = NodeArgs::checked_extract(&inst.bound, &indexes)?;

            let attrs = &mut ty.attrs;

            let sub_target = Inst::subscriber();
            attrs.insert(0, parse_quote!(#[#sub_target(#node_args)]));

            cfg_feature_disclaimer(ty);
        }

        let attrs = &mut transform.attrs;
        let support_crate = Inst::support_crate();
        let node_target = Inst::node_target();
        attrs.insert(
            0,
            parse_quote!(#[#support_crate::#node_target]),
        );
        Inst::delegate_attribute(attrs);

        Ok(())
    }

    fn validate_transform(
        &self,
        transform: &ItemTrait,
        _: Option<&()>,
    ) -> Result<(), proc_macro2::TokenStream> {
        let support_crate = Inst::support_crate();
        let Some(delegate_macro) = Inst::delegate_macro() else {
            return Err(TraitBug::DelegateMacroNotInitialized {}.into());
        };

        let Some((idx, inst_attr)) = transform.attrs.iter().enumerate().find_map(|(i, attr)| {
            let node_target = Inst::node_target();
            if *attr.path() == parse_quote!(#support_crate::#node_target) {
                return Some((i, attr));
            }
            return None;
        }) else {
            return Err(TraitBug::InstanceTraitNodeMacroNotFound {}.into());
        };

        if !transform.attrs.iter().enumerate().any(|(i, attr)| {
            if i <= idx {
                return false;
            }
            *attr.path() == parse_quote!(#support_crate::#delegate_macro)
        }) {
            return Err(TraitBug::DelegateMacroNotFound {}.into());
        }

        let syn::Meta::Path(_) = &inst_attr.meta else {
            return Err(TraitBug::InstanceTraitNodeMacroArgsFound {}.into());
        };

        let node = Inst::node();

        for item in &transform.items {
            match item {
                TraitItem::Const(c) => {
                    if c.attrs.iter().any(|attr| attr.path().is_ident(&node)) {
                        return Err(TraitBug::NodeOnlyInTypeAssoc {}.into());
                    }
                }
                TraitItem::Fn(f) => {
                    if f.attrs.iter().any(|attr| attr.path().is_ident(&node)) {
                        return Err(TraitBug::NodeOnlyInTypeAssoc {}.into());
                    }
                }
                TraitItem::Type(ty) => {
                    if !ty
                        .attrs
                        .iter()
                        .any(|attr| attr.path().is_ident(&Inst::subscriber()))
                    {
                        continue;
                    }
                    // rest validation requires re-parsing which is not required
                }
                _ => {}
            }
        }

        Ok(())
    }
}

// ===============================================================================
// ```````````````````````````` INST ASSOC TYPE TUPLE ````````````````````````````
// ===============================================================================

/// Visits const generic parameters and replaces `Self` references with the
/// generated holder type.
/// 
/// ```ignore
/// Self -> <holder as trait_path>
/// ```
///
/// The holder represents the concrete trait implementation, while the trait
/// path provides the qualified path used to resolve associated types.
struct ConstParamVisitor<'a> {
    /// The generated holder type.
    holder: &'a Ident,

    /// The trait path used to qualify `Self` references.
    trait_path: &'a Path,
}


impl<'a> VisitMut for ConstParamVisitor<'a> {
    fn visit_type_path_mut(&mut self, ty: &mut syn::TypePath) {
        if ty
            .path
            .segments
            .first()
            .is_some_and(|segment| segment.ident == "Self")
        {
            let holder = self.holder;
            let trait_path = self.trait_path;

            let position = trait_path.segments.len();

            let mut segments = syn::punctuated::Punctuated::new();

            segments.extend(trait_path.segments.iter().cloned());
            segments.extend(ty.path.segments.iter().skip(1).cloned());

            ty.path.segments = segments;

            ty.qself = Some(syn::QSelf {
                lt_token: syn::token::Lt::default(),
                ty: Box::new(syn::parse_quote!(#holder)),
                position,
                as_token: Some(syn::token::As::default()),
                gt_token: syn::token::Gt::default(),
            });

            return;
        }

        visit_mut::visit_type_path_mut(self, ty);
    }
}

/// Transforms instance tuple associated types declared on an instance trait.
///
/// The transformation operates on [`TraitItem::Type`] items containing the
/// `#[tuple(...)]` attribute. Each such associated type declares an instance
/// tuple whose members are exposed as generated instance types.
///
/// For each matching associated type, the transformation:
///
/// - locates and validates the `#[tuple(...)]` attribute,
/// - rejects unsupported associated-type `where` clauses,
/// - extracts the declared associated-type bounds and preserves them for
///   documentation,
/// - replaces the declared bounds with the generated `InstTuple` bound,
/// - extracts the tuple declaration and converts it into instance node
///   arguments,
/// - attaches the generated `#[instance_sub(...)]` attribute,
/// - adds the feature-specific documentation disclaimer,
/// - generates the associated type implementation used as the instance
///   tuple representation, and
/// - generates the instance access implementations for the destructured
///   tuple members.
///
/// For each tuple member, the transformation generates an associated type
/// resolving the member to `Self::Variant`. The member is then passed through
/// the instance access machinery so that it can be resolved as an instance
/// node through the generated access path.
///
/// A documentation-only type alias is also generated for each tuple member
/// when the `inst` feature is disabled. These aliases preserve the visible
/// tuple type and its generic parameters for generated documentation.
///
/// Generates the instance tuple representation together with access
/// implementations for declared tuple types. Under the `inst` feature, those
/// members resolve through the instance tuple implementation; without the
/// feature, the generated aliases provide the corresponding documentation
/// representation.
#[derive(Debug, Clone)]
struct ItemTypeTupleInst;

impl<'a> Transformation<AddonSpace<'a>> for ItemTypeTupleInst {
    fn raw_transform(
        &self,
        transform: &mut AddonSpace<'a>,
        _: &(),
    ) -> Result<(), proc_macro2::TokenStream> {
        let (file, transform) = transform;

        let mut ty_items = Vec::new();
        let tuple = Inst::tuple();
        for item in &mut transform.items {
            if let TraitItem::Type(t) = item {
                if t.attrs.iter().any(|attr| attr.path().is_ident(&tuple)) {
                    ty_items.push(t);
                }
            }
        }

        let mut lt_params: Punctuated<GenericParam, Comma> = Punctuated::new();
        let mut ty_params: Punctuated<GenericParam, Comma> = Punctuated::new();
        let mut ct_params: Punctuated<GenericParam, Comma> = Punctuated::new();
        for param in &transform.generics.params {
            match param {
                GenericParam::Lifetime(lt) => {
                    let mut lt = lt.clone();
                    lt.bounds = Punctuated::new();
                    lt_params.push(GenericParam::Lifetime(lt.clone()));
                },
                GenericParam::Type(ty) => {
                    let mut ty = ty.clone();
                    ty.bounds = Punctuated::new();
                    ty_params.push(GenericParam::Type(ty.clone()));
                },
                GenericParam::Const(c) => {
                    ct_params.push(GenericParam::Const(c.clone()));
                },
            }
        }
        let _ = lt_params.pop_punct();
        let _ = ty_params.pop_punct();
        let _ = ct_params.pop_punct();

        let (_, generic_types, _) = transform.generics.split_for_impl();
        let trait_ident = &transform.ident;

        let support_crate = Inst::support_crate();

        for ty in ty_items {

            if let Some(where_clause) = &ty.generics.where_clause {
                return Err(TraitError::WhereClauseNotSupportInTuple { where_: where_clause.clone() }.into());
            }

            let param_bounds = ty.bounds.clone();
            ty.bounds = Punctuated::new();

            let bounds_len = param_bounds.len();
            let mut param_bounds_docs = Vec::new();
            for (i, bound) in param_bounds.iter().enumerate() {
                param_bounds_docs.push(DocAttr::Ref(type_param_bound_to_string(bound)));
                if i < bounds_len - 1 {
                    param_bounds_docs.push(DocAttr::Raw(" + ".to_string()));
                }
            }

            let trait_bound: TraitBound = parse_quote!(#support_crate::InstTuple<0, Variant: #param_bounds>);
            ty.bounds.push(TypeParamBound::Trait(trait_bound));

            let mut tuple_attr = None;
            let mut build = Vec::new();
            for attr in &ty.attrs {
                if !attr.path().is_ident(&tuple) {
                    build.push(attr.clone());
                    continue;
                }
                if tuple_attr.is_some() {
                    return Err(TraitError::DoubleTuple { attr: attr.clone() }.into());
                };
                tuple_attr = Some(attr.clone());
            }
            ty.attrs = build;
            let Some(tuple_attr) = tuple_attr else {
                return Err(TraitBug::InconsistencyFindingTupleAttribute {}.into());
            };

            let tokens = match &tuple_attr.meta {
                syn::Meta::List(meta_list) => &meta_list.tokens,
                syn::Meta::Path(_) => {
                    return Err(TraitError::TupleRequiresArgs {
                        attr: tuple_attr.clone(),
                    }
                    .into());
                }
                syn::Meta::NameValue(meta) => {
                    return Err(TraitError::TupleRequiresArgsNotValue { meta: meta.clone() }.into());
                }
            };
            if tokens.is_empty() {
                return Err(TraitError::TupleRequiresArgs {
                    attr: tuple_attr.clone(),
                }
                .into());
            }

            let mut indexes = IntList::default();
            indexes.ints.push(LitInt::new("0", Span::call_site()));

            let inst = InstTupleArgs::checked_extract(tokens, &())?;

            let node_args = NodeArgs::checked_extract(&inst.clone().into(), &indexes)?;

            let attrs = &mut ty.attrs;

            let sub_target = Inst::subscriber();
            attrs.insert(0, parse_quote!(#[#sub_target(#node_args)]));

            cfg_feature_disclaimer(ty);

            let assoc_ident = &ty.ident;
            let (_, assoc_generics, _) = &ty.generics.split_for_impl();
            let combined_path: Path = parse_quote!(#trait_ident::#assoc_ident #assoc_generics);
            let holder = format_ident!("T");
            let trait_arg: Path = parse_quote!(#trait_ident #generic_types);

            let mut generics: Punctuated<GenericParam, Comma> = Punctuated::new();
            generics.extend(lt_params.clone());
            generics.push(parse_quote!(#holder: #trait_arg));
            generics.extend(ty_params.clone());
            let mut ct_params = ct_params.clone();
            let mut visitor = ConstParamVisitor {holder: &holder, trait_path: &trait_arg};
            for param in &mut ct_params {
                let GenericParam::Const(c) = param else {
                    unreachable!()
                };
                visitor.visit_const_param_mut(c);
            }
            generics.extend(ct_params);

            let assoc_type: Type = parse_quote!(<#holder as #trait_arg>::#assoc_ident #assoc_generics);
            let addon_impl : ItemImpl = parse_quote!(
                impl<#generics> #assoc_type 
                where 
                    Self: #support_crate::InstTuple<0> 
                {}
            );

            let mut impl_types = Vec::new();
            for tuple in &inst.list {
                let vis = &tuple.visibility;
                let ident = &tuple.ident;

                let mut impl_type: ImplItemType = parse_quote!(#vis type #ident = Self::Variant;);
                impl_type.attrs.push(parse_quote!(#[allow(non_camel_case_types)]));
                impl_type.attrs.push(parse_quote!(#[allow(unused)]));
                impl_type.attrs.push(parse_quote!(#[allow(type_alias_bounds)]));

                let mut doc_type :ItemType = parse_quote!(#vis type #ident<#generics> = #assoc_type;);
                doc_type.attrs.push(parse_quote!(#[allow(non_camel_case_types)]));
                doc_type.attrs.push(parse_quote!(#[allow(unused)]));
                doc_type.attrs.push(parse_quote!(#[allow(type_alias_bounds)]));

                impl_types.push((ident.clone(), impl_type, doc_type));
            }

            for (ident, mut not_doc_ty, mut doc_ty) in impl_types {

                let mut params = Punctuated::new();
                let span = ident.span();
                params.push(crate::args::InstanceIdent::Compile(ident));
                let inst = InstanceModel::Simple(InstanceIdents {span, paren_token: Default::default(), params });

                // Indexes are placeholder, for impl nodes in instances-macro their length is only taken
                let mut indexes = IntList::default();
                for i in 0..InstModelLength::checked_extract(&inst, &())?.0 {
                    indexes
                        .ints
                        .push(LitInt::new(&i.to_string(), Span::call_site()));
                }
                let access = AccessArgsRef(inst);
                let args = access.try_leaf(&indexes).unwrap();

                let mut doc_ty_docs = Vec::new();
                doc_ty_docs.extend( vec![
                    DocAttr::Heading {
                        level: 0,
                        content: vec![
                            DocAttr::Raw(
                                "Instance Tuple Type ".to_string(),
                            ),
                            DocAttr::Ref(path_to_string(&combined_path)),
                        ],
                    },
                    DocAttr::Raw("Implements bounds: ".to_string())
                    ]
                );
                doc_ty_docs.extend(param_bounds_docs.clone());
                doc_ty_docs.extend(vec![
                    DocAttr::LineBreak,
                    DocAttr::Raw(
                        "Destructured Instance Tuple Type with well-defined bounds while used with cfg `--features inst`."
                            .to_string(),
                    ),
                    DocAttr::LineBreak,
                    DocAttr::Raw(
                        "*See* ".to_string(),
                    ),
                    DocAttr::Link {
                        title: "`inst::tuple`".to_string(),
                        url: "inst::tuple".to_string(),
                    },
                    DocAttr::Raw(
                        " *for details.*".to_string(),
                    ),
                    DocAttr::LineBreak,
                ]);
                doc_ty.prepend_docs(doc_ty_docs);
                doc_ty.attrs.insert(0, Inst::not_feature());
                file.items.push(Item::Type(doc_ty));

                cfg_feature_disclaimer(&mut not_doc_ty);
                not_doc_ty.attrs.insert(0, Inst::feature());

                let mut not_doc_version = addon_impl.clone();
                not_doc_version.items.push(syn::ImplItem::Type(not_doc_ty));
                not_doc_version.attrs.push(Inst::feature());
                let access_target = Inst::access_target();
                not_doc_version.attrs.push(parse_quote!(#[#support_crate::#access_target(#args)]));
                Inst::delegate_attribute(&mut not_doc_version.attrs);
                file.items.push(Item::Impl(not_doc_version));

            }

        }

        let attrs = &mut transform.attrs;
        let support_crate = Inst::support_crate();
        let node_target = Inst::node_target();
        attrs.insert(
            0,
            parse_quote!(#[#support_crate::#node_target]),
        );
        Inst::delegate_attribute(attrs);

        Ok(())
    }

    fn validate_transform(
        &self,
        transform: &AddonSpace<'a>,
        context: Option<&()>,
    ) -> Result<(), proc_macro2::TokenStream> {
        let (file, transform) = transform;
        ItemTypeNodeInst::validate_transform(&ItemTypeNodeInst, transform, context)?;

        let support_crate = Inst::support_crate();
        let access_target = Inst::access_target();
        let trait_generics = &transform.generics;
        let (_, generic_types, _) = trait_generics.split_for_impl();
        let trait_ident = &transform.ident;
        let trait_path_seg: PathSegment = parse_quote!(#trait_ident #generic_types);
        let holder = format_ident!("T");
        let holder_index = trait_generics
            .params
            .iter()
            .position(|param| !matches!(param, GenericParam::Lifetime(_)))
            .unwrap_or(trait_generics.params.len());

        let has_type_attrs = |attrs: &Vec<Attribute>| -> Result<(), TokenStream> {
            if !attrs.iter().any(|attr| {
                match &attr.meta {
                    Meta::List(list) => {
                        if !list.path.is_ident("allow") {
                            return false
                        }

                        list.tokens.to_string() == quote!(non_camel_case_types).to_string()
                    }
                    _ => false,
                }
            }) {
                return Err(TraitBug::TraitTupleTargetItemNonCamelCaseAttrMissing {}.into())
            }

            if !attrs.iter().any(|attr| {
                match &attr.meta {
                    Meta::List(list) => {
                        if !list.path.is_ident("allow") {
                            return false
                        }

                        list.tokens.to_string() == quote!(type_alias_bounds).to_string()
                    }
                    _ => false,
                }
            }) {
                return Err(TraitBug::TraitTupleTargetItemTypeAliasBoundsAttrMissing {}.into())
            }

            if !attrs.iter().any(|attr| {
                match &attr.meta {
                    Meta::List(list) => {
                        if !list.path.is_ident("allow") {
                            return false
                        }

                        list.tokens.to_string() == quote!(unused).to_string()
                    }
                    _ => false,
                }
            }) {
                return Err(TraitBug::TraitTupleTargetItemUnusedAttrMissing {}.into())
            }
            Ok(())
        };

        let mut expected_docs = Vec::new();
        for addon in &file.items {
            let impl_ = match addon {
                Item::Impl(impl_) => impl_,
                Item::Type(_) => {
                    continue;
                },
                _ =>  return Err(TraitBug::TraitTupleExpectedAddonNotImplNorTypeAlias {}.into())
            };

            if !impl_.attrs.iter().any(|attr| {
                match &attr.meta {
                    Meta::List(list) => {
                        if !list.path.is_ident("cfg") {
                            return false
                        }

                        list.tokens.to_string() == quote!(feature = "inst").to_string()
                    }
                    _ => false,
                }
            }) {
                return Err(TraitBug::TraitTupleExpectedAddonAccessImplNotFeatureGated {}.into())
            }

            if !impl_.attrs.iter().any(|attr| *attr.path() == parse_quote!(#support_crate::#access_target)) {
                return Err(TraitBug::TraitTupleExpectedAddonAccessImplArgsNotFound {}.into())
            }

            let self_ty = &*impl_.self_ty;

            let Type::Path(path) = &*self_ty else {
                return Err(TraitBug::TraitTupleAddonAccessImplSelfNotTypePath {}.into())
            };

            let Some(qself) = &path.qself else {
                return Err(TraitBug::TraitTupleAddonAccessImplSelfNotAssoc {}.into())
            };

            if qself.as_token.is_none() {
                return Err(TraitBug::TraitTupleAddonAccessImplSelfNotAssoc {}.into())
            }

            if qself.ty != parse_quote!(#holder) {
                return Err(TraitBug::TraitTupleAddonAccessImplSelfAssocQSelfInvalid {}.into())
            }

            let mut segments = path.path.segments.iter();

            let Some(trait_seg) = segments.next() else {
                return Err(TraitBug::TraitTupleAddonAccessImplSelfAssocTraitNotFound {}.into())
            };

            if *trait_seg != trait_path_seg {
                return Err(TraitBug::TraitTupleAddonAccessImplSelfAssocTraitInvalid {}.into())
            }

            let Some(last) = segments.next() else {
                return Err(TraitBug::TraitTupleAddonAccessImplSelfAssocNotFound {}.into())
            };

            if segments.peekable().peek().is_some() {
                return Err(TraitBug::TraitTupleAddonAccessImplSelfInconsistent {}.into())
            }


            if !transform.items.iter().any(|item| {
                let TraitItem::Type(ty) = item else {
                    return false;
                };

                ty.ident == last.ident
            }) {
                return Err(TraitBug::TraitTupleAddonAccessImplForUnknownNode {}.into())
            }

            let generics = &impl_.generics;

            let Some(where_clause) = &generics.where_clause else {
                return Err(TraitBug::TraitTupleAddonAccessImplWhereClauseMissing {}.into())
            };

            if where_clause.predicates.len() > 1 {
                return Err(TraitBug::TraitTupleAddonAccessImplInconsistentWhereClausePreds {}.into())
            }

            let syn::WherePredicate::Type(ty) = &where_clause.predicates[0] else {
                return Err(TraitBug::TraitTupleAddonAccessImplNotTypePred {}.into())
            };

            if ty.bounded_ty != parse_quote!(Self) {
                return Err(TraitBug::TraitTupleAddonAccessImplTypePredNotSelf {}.into())
            }

            if ty.bounds.len() > 1 {
                return Err(TraitBug::TraitTupleAddonAccessImplSelfPredBoundsInconsistent {}.into())
            }

            if ty.bounds[0] != parse_quote!(#support_crate::InstTuple<0>) {
                return Err(TraitBug::TraitTupleAddonAccessImplInvalidSelfInstBound {}.into())
            }

            if generics.params.len() != trait_generics.params.len() + 1 {
                return Err(TraitBug::TraitTupleAddonAccessImplGenericParamsLenInvalid {}.into())
            }

            let Some(holder_param) = generics.params.iter().find_map(|param| {
                if let GenericParam::Type(ty) = param {
                    return Some(ty)
                }
                return None
            }) else {
                return Err(TraitBug::TraitTupleAddonAccessImplHolderGenericParamTypeMissing {}.into())
            };

            if holder_param.ident != holder {
                return Err(TraitBug::TraitTupleAddonAccessImplHolderParamWrongIdent {}.into())
            }

            if holder_param.bounds.len() > 1 {
                return Err(TraitBug::TraitTupleAddonAccessImplHolderParamExtraBounds {}.into())
            }

            let TypeParamBound::Trait(holder_bound) = &holder_param.bounds[0] else {
                return Err(TraitBug::TraitTupleAddonAccessImplHolderParamNotTypeBound {}.into())
            };

            if *holder_bound != parse_quote!(#trait_path_seg) {
                return Err(TraitBug::TraitTupleAddonAccessImplHolderParamBoundInvalid {}.into())
            }

            let mut trait_params_cloned = trait_generics.params.clone();
            trait_params_cloned.insert(holder_index, GenericParam::Type(holder_param.clone()));

            let mut seen = false;
            for (param, t_param) in generics.params.iter().zip(trait_params_cloned) {
                match (param, t_param) {
                    (GenericParam::Lifetime(lt0), GenericParam::Lifetime(lt1)) => {
                        if !lt0.bounds.is_empty() {
                            return Err(TraitBug::TraitTupleAddonAccessImplLifetimeParamHasBounds {}.into())
                        }

                        if lt0.lifetime.ident != lt1.lifetime.ident {
                            return Err(TraitBug::TraitTupleAddonAccessImplLifetimeIdentInvalid {}.into())
                        }
                    },
                    (GenericParam::Type(ty0), GenericParam::Type(ty1)) => {
                        if !seen {
                            seen = true;
                            continue;
                        }
                        if !ty0.bounds.is_empty() {
                            return Err(TraitBug::TraitTupleAddonAccessImplTypeParamHasBounds {}.into())
                        }

                        if ty0.ident != ty1.ident {
                            return Err(TraitBug::TraitTupleAddonAccessImplTypeParamIdentInvalid {}.into())
                        }
                    },
                    (GenericParam::Const(c0), GenericParam::Const(mut c1)) => {
                        let mut visitor = ConstParamVisitor {holder: &holder, trait_path: &parse_quote!(#trait_path_seg)};
                        visitor.visit_const_param_mut(&mut c1);

                        if c0.default != c1.default {
                            return Err(TraitBug::TraitTupleAddonAccessImplConstParamInvalidDefault {}.into())
                        }
                        if c0.ty != c1.ty {
                            return Err(TraitBug::TraitTupleAddonAccessImplConstParamInvalidType {}.into())

                        }
                        if c0.ident != c1.ident {
                            return Err(TraitBug::TraitTupleAddonAccessImplConstParamInvalidIdent {}.into())
                        }
                    },
                    _ => return Err(TraitBug::TraitTupleAddonAccessImplInvalidGenericParam {}.into())
                };
            }

            if impl_.items.len() > 1 {
                return Err(TraitBug::TraitTupleAddonAccessImplExtraItemsFound {}.into())
            }

            let ImplItem::Type(ty) = &impl_.items[0] else {
                return Err(TraitBug::TraitTupleAddonAccessImplItemNotType {}.into())
            };

            let vis = &ty.vis;
            let ident = &ty.ident;

            if ty.ty != parse_quote!(Self::Variant) {
                return Err(TraitBug::TraitTupleAddonAccessImplItemInvalidType {}.into())
            }

            has_type_attrs(&ty.attrs)?;

            expected_docs.push((vis, ident, self_ty.clone()));

        }

        for (vis, ident, self_ty) in expected_docs {
            let Some(ty) = file.items.iter().find_map(|item| {
                let Item::Type(ty) = item else {
                    return None 
                };

                if ty.ident == *ident {
                    return Some(ty)
                }

                return None
            }) else {
                return Err(TraitBug::TraitTupleAddonExpectedDocTypeAliasNotFound {}.into())
            };

            has_type_attrs(&ty.attrs)?;

            if !ty.attrs.iter().any(|attr| {
                match &attr.meta {
                    Meta::List(list) => {
                        if !list.path.is_ident("cfg") {
                            return false
                        }

                        list.tokens.to_string() == quote!(not(feature = "inst")).to_string()
                    }
                    _ => false,
                }
            }) {
                return Err(TraitBug::TraitTupleExpecteDocTypeAliasNotNotFeatureGated {}.into())
            }


            if *ty.ty != self_ty {
                return Err(TraitBug::TraitTupleExpecteDocTypeAliasInvalidType {}.into())
            }

            if ty.vis != *vis {
                return Err(TraitBug::TraitTupleExpecteDocTypeAliasInvalidVisibility {}.into())
            }

            if !ty.attrs.clone().has_docs() {
                return Err(TraitBug::TraitTupleExpecteDocTypeAliasHasNoDocs {}.into())
            }
        }


        Ok(())
    }
}


// ===============================================================================
// `````````````````````````````` HELPER FUNCTIONS ```````````````````````````````
// ===============================================================================

/// A trait-bound is matched against `path`. The matching trait bound is removed,
/// its instance arguments are appended after lifetime arguments, and the
/// transformed bound is inserted at the beginning of the bounds list.
///
/// If `push_args` is `true`, each instance parameter position receives a
/// placeholder const argument (`0`). If `false`, only the positions are
/// calculated and returned.
///
/// Before:
///
/// ```ignore
/// T: Crypto::Hasher + Send
/// ```
///
/// After with `bound = (Module, Function)` and `push_args = true`:
///
/// ```ignore
/// T: Crypto::Hasher<0, 0> + Send
/// ```
///
/// The returned [`IntList`] contains the generic argument positions of the
/// inserted instance counters.
pub fn append_placeholder_args(
    bounds: &mut Punctuated<TypeParamBound, Plus>,
    path: &Punctuated<Ident, PathSep>,
    bound: &InstanceModel,
    push_args: bool,
) -> Result<IntList, TokenStream> {
    let mut found = None;
    let mut build = Punctuated::<TypeParamBound, Plus>::new();

    for t_bound in bounds.iter() {
        let TypeParamBound::Trait(trait_) = t_bound else {
            build.push(t_bound.clone());
            continue;
        };

        let trait_path = trait_.path.segments.iter().map(|seg| &seg.ident).rev();
        let asked = path.iter().rev();

        if asked.len() != trait_path.len() {
            build.push(t_bound.clone());
            continue;
        }

        if asked.zip(trait_path).all(|(given, orig)| given == orig) {
            if found.is_some() {
                return Err(TraitError::DuplicateInstanceTraitBound {
                    bound: trait_.clone(),
                }
                .into());
            }

            found = Some(trait_.clone());
            continue;
        }

        build.push(t_bound.clone());
    }

    *bounds = build;

    let Some(mut trait_bound) = found else {
        return Err(TraitError::ExpectedInstTraitNodeBound {
            bounds: bounds.clone(),
            exp: path.clone(),
        }
        .into());
    };

    let indexes = append_placeholder_args_to_trait(&mut trait_bound.path, bound, push_args)?;

    bounds.insert(0, TypeParamBound::Trait(trait_bound));

    Ok(indexes)
}

/// Appends placeholder instance arguments to an instance-trait path.
///
/// The instance arguments are inserted after all lifetime arguments. One
/// position is produced for each parameter in the [`InstanceModel`].
///
/// With `push_args` enabled, a `0` const argument is inserted at each
/// position; otherwise only the positions are returned.
///
/// ```ignore
/// Crypto::Hasher<'a, T>
/// ```
///
/// with two instance parameters becomes:
///
/// ```ignore
/// Crypto::Hasher<'a, 0, 0, T>
/// ```
///
/// The returned [`IntList`] contains the positions at which the instance
/// arguments were inserted.
pub fn append_placeholder_args_to_trait(
    path: &mut syn::Path,
    bound: &InstanceModel,
    push_args: bool,
) -> Result<IntList, TokenStream> {
    let args = &mut path.segments.last_mut().unwrap().arguments;

    let angle = match args {
        PathArguments::None => {
            *args = PathArguments::AngleBracketed(AngleBracketedGenericArguments {
                colon2_token: Default::default(),
                lt_token: Default::default(),
                args: Default::default(),
                gt_token: Default::default(),
            });

            let PathArguments::AngleBracketed(angle) = args else {
                unreachable!()
            };

            angle
        }

        PathArguments::AngleBracketed(angle) => angle,

        PathArguments::Parenthesized(paren) => {
            return Err(TraitError::ParenthesizedInstTraitNodeBound {
                paren: paren.clone(),
            }
            .into());
        }
    };

    // Only append params after lifetimes.
    let mut seen_non_lifetime = false;

    for param in angle.args.iter() {
        if let GenericArgument::Lifetime(lt) = param {
            if seen_non_lifetime {
                return Err(ProcParseErr::LifetimeShouldBeDeclaredFront { lt: lt.clone() }.into());
            }
        } else {
            seen_non_lifetime = true;
        }
    }

    let index = angle
        .args
        .iter()
        .position(|param| !matches!(param, GenericArgument::Lifetime(_)))
        .unwrap_or(angle.args.len());

    let mut indexes = IntList::default();

    for offset in 0..InstModelLength::checked_extract(bound, &())?.0 {
        let offsetted = index + offset;

        if push_args {
            angle
                .args
                .insert(offsetted, GenericArgument::Const(parse_quote!(0)));
        }

        indexes
            .ints
            .push(LitInt::new(&offsetted.to_string(), Span::call_site()));
    }

    if angle.args.is_empty() {
        *args = PathArguments::None;
    }

    Ok(indexes)
}

/// Prepends a inst cfg feature documentation disclaimer.
pub fn cfg_feature_disclaimer<T: InsertDocs>(item: &mut T) {
    item.prepend_docs(vec![
        DocAttr::Raw(
            "*Note: This is an internal expansion of `cfg(feature = \"inst\")`*"
                .to_string(),
        ),
        DocAttr::Bullet {
            level: 0,
            content: vec![DocAttr::Raw(
                "This may include internal proc-macro expansions which should not be used in user scope as it may be susceptible to change."
                    .to_string(),
            )],
        },
        DocAttr::Bullet {
            level: 0,
            content: vec![DocAttr::Raw(
                "For authoritative documentation, rely on plain generated rustdoc (`cargo doc`) or docs.rs output."
                    .to_string(),
            )],
        },
        DocAttr::Bullet {
            level: 0,
            content: vec![DocAttr::Raw(
                "For build, rely on feature `cargo build --features inst` output."
                    .to_string(),
            )],
        },
        DocAttr::LineBreak,
    ]);
}

/// Converts a syntax path into its compact token representation.
///
/// The generated string removes the whitespace introduced around path
/// separators and generic angle brackets by [`TokenStream::to_string`].
///
/// For example:
///
/// ```ignore
/// Foo < Bar > ::Baz
/// ```
///
/// is converted to:
///
/// ```text
/// Foo<Bar>::Baz
/// ```
fn path_to_string(path: &syn::Path) -> String {
    path.to_token_stream()
        .to_string()
        .replace(" :: ", "::")
        .replace(" < ", "<")
        .replace(" > ", ">")
}

/// Converts a type parameter bound into its normalized string representation.
///
/// Trait bounds are represented from their contained path and normalized using
/// [`path_to_string`]. Lifetime bounds are converted from their token
/// representation with whitespace removed.
///
/// Other bound forms are converted from their token representation and
/// normalized by removing whitespace around path separators and generic
/// angle brackets.
fn type_param_bound_to_string(bound: &syn::TypeParamBound) -> String {
    match bound {
        syn::TypeParamBound::Trait(bound) => 
        {
            let path = &bound.path;
            path_to_string(path)
        } 

        syn::TypeParamBound::Lifetime(lifetime) => {
            lifetime.to_token_stream().to_string().replace(" ", "")
        }

        _ => bound.to_token_stream().to_string().replace(" :: ", "::")
        .replace(" < ", "<")
        .replace(" > ", ">"),
    }
}